### ISSUE TITLE
Product type output twice

### ISSUE THREAD

**Issue by djsunrise19** [raywo/MMM-PublicTransportHafas#33]
Hi,

the product type seems to be there twice:
<img width="365" alt="bildschirmfoto 2018-02-19 um 19 29 00" src="https://user-images.githubusercontent.com/14234570/36392655-9a8e2f42-15ac-11e8-94fd-99ec1e3954fa.png">

stationID: "008000728"
direction: "008000105"

Best regards,
Maurice

**Comment by raywo** [comment]
Fixed with pr #35

**Comment by djsunrise19** [comment]
Hi!

Now it stucks on "loading". Here is my config:

```
{
  module: "MMM-PublicTransportHafas",
  position: "top_left",

  config: {
    stationID: "008000728",                   // Replace with your stationID!
    stationName: "Bad Nauheim (Richtung Frankfurt)",   // Replace with your station name!

    direction: "008000105",                    // Show only departures heading to this station. (A station ID.)
    ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
    updatesEvery: 60,
    excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
    timeToStation: 15,                // How long do you need to walk to the next Station?
    timeInFuture: 90,                 // Show departures for the next *timeInFuture* minutes.

    showColoredLineSymbols: true,     // Want colored line symbols?
    useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
    showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
    maxUnreachableDepartures: 2,      // How many unreachable departures should be shown?
    maxReachableDepartures: 4,        // How many reachable departures should be shown?
    //customLineStyles: "",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
    showOnlyLineNumbers: false        // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"
  }
}, 
```

**Comment by raywo** [comment]
Please open the dev tools of your browser and have a look in the console. Is there any error listed?

It works for me. Did you execute `git pull && nom install` to update the module?

**Comment by djsunrise19** [comment]
Looks like an temporary issue. Now, it works! Thank you!

**Comment by djsunrise19** [comment]
I don't want to open another issue, but I have a short question. After the newest update, the departures doesn't seem to be correct. I display departures for the next 90min. In 60min there will be a train. But the module says: No connections, actually.

At the bottom, there is the MMM-PublicTransportDB module with the same settings.
<img width="411" alt="bildschirmfoto 2018-02-19 um 22 28 50" src="https://user-images.githubusercontent.com/14234570/36397783-5a172140-15c4-11e8-8788-dec25584ffe6.png">

**Comment by raywo** [comment]
I think that has to do with your direction. If you leave direction blank there are departures. Maybe you should use another ID. It doesn’t need to be the final station. Just a station on the route is sufficient.

**Comment by djsunrise19** [comment]
You are right! Frankfurt Main has two ID's for HBF. I took the other one, now it works. I don't know, why it worked before (with the other id). Thank you again and good night :-D.
