### ISSUE TITLE
Cancelled connections are displayed as in time

### ISSUE THREAD

**Issue by khassel** [raywo/MMM-PublicTransportHafas#55]
Hi,
today no U-Trains are driving in Frankfurt/Main and I'm a little confused that my mirror is displaying them as in time:
![grafik](https://user-images.githubusercontent.com/25914086/38045818-34f6b85a-32be-11e8-941c-e522afa40a6f.png)
In reality there is no U8 and no U9 driving.
My setup:
```
		{
			module: "MMM-PublicTransportHafas",
			position: "top_right",

			config: {
				stationID: "000102978",             // Replace with your stationID!
				stationName: "Uni Campus Riedberg", // Replace with your station name!

				direction: "",                    // Show only departures heading to this station. (A station ID.)
				ignoredLines: [],                 // Which lines should be ignored? (comma-separated list of line names)
				excludedTransportationTypes: [],  // Which transportation types should not be shown on the mirror? (comma-separated list of types) possible values: StN for tram, BuN for bus, s for suburban
				timeToStation: 3,                 // How long do you need to walk to the next Station?
				timeInFuture: 60,                 // Show departures for the next *timeInFuture* minutes.

				showColoredLineSymbols: true,     // Want colored line symbols?
				useColorForRealtimeInfo: true,    // Want colored real time information (timeToStation, early)?
				showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
				maxUnreachableDepartures: 1,      // How many unreachable departures should be shown?
				maxReachableDepartures: 7,        // How many reachable departures should be shown?
				customLineStyles: "leipzig",      // Prefix for the name of the custom css file. ex: Leipzig-lines.css (case sensitive)
				showOnlyLineNumbers: false,        // Display only the line number instead of the complete name, i. e. "11" instead of "STR 11"

				updatesEvery: 60,
				marqueeLongDirections: false,
			}
		},
```
Any ideas?
Thanks,
Karsten.

**Comment by derhuerst** [comment]
The underlying library [`hafas-client`](https://github.com/public-transport/hafas-client) has recently got support for cancelled departures. This project would have to upgrade.

But independently of that, the API endpoint being queried might give wrong data.

**Comment by khassel** [comment]
today again no U-Trains are driving in Frankfurt but now it works as expected: Only bus departures are visible, no U-Train departures ... This module hasn't changed, so maybe this was fixed in the hafas-client?

**Comment by derhuerst** [comment]
As I said, `hafas-client` now exposes the information from the API that a departure has been cancelled. You need to update for that though.

What could also be the case: The API doesn't return the departure in the first place, not even as canceled.
