### ISSUE TITLE
Issues with specific stationID

### ISSUE THREAD

**Issue by TimoBS** [raywo/MMM-PublicTransportHafas#65]
Since some weeks I'm facing the issue that only the `stationID: "000890723"` for the Station _"Am Bruchkamp"_ in _Braunschweig, Germany_ does not work any longer. 
Now I´ve to use previous `stationID: "000890650"` instead. 
Does anybody have the same issue with some stationIDs or may try if mine does work for him?
I also double checked with the script `node ./convenience/query_stations.js` if the stationID was changed but it´s still the same.
Any other ideas?

**Comment by derhuerst** [comment]
Author of the underlying API client `hafas-client` here.

Please provide your full setup:

- version of your `MMM-PublicTransportHafas` installation
- what does "does not work anymore" mean? does it show an error or 0 results?
- did you use any custom configuration, e.g. the direction?

I just fetched departures at `000890723` using a newer version of the underlying [`hafas-client` library](https://github.com/public-transport/hafas-client) and it worked.

**Comment by TimoBS** [comment]
Good news that `stationID: „000890723“` does work in general.
The request should result in Bus 416 and Bus 433 in two different directions (e.g. Bus 416 to "Kralenriede" and "Völkenrode"). 

- Run the latest version of `MMM-PublicTransportHafas` with following hash
```
~/MagicMirror/modules/MMM-PublicTransportHafas $ git rev-parse HEAD
126b94b96c5c9bfde50053983166424c5106f832
```

- "does not work anymore" means that I got zero results back and no errors are shown. Without change or update anything. Just stops working with my custom config. 

- running on following custom configuration including directions:
```
{
disabled: false,
module: "MMM-PublicTransportHafas",
position: "top_center",
config: {
     stationID: "000890723",
     stationName: "Abfahrtstafel - Am Bruchkamp",
     direction: "000890724",
     timeToStation: 3,
     showColoredLineSymbols: true,
     useColorForRealtimeInfo: true,
     showTableHeadersAsSymbols: false,
     maxUnreachableDepartures: 0,
     maxReachableDepartures: 5,
     showOnlyLineNumbers: false,
     }
}
```

With the following "simple config" I got also some results but only Bus connections in direction "Völkenrode" and not for the other direction "Kralenriede". Seems that with the `direction` I do filter all results to zero.

```
{
 disabled: false,
 module: "MMM-PublicTransportHafas",
 position: "top_center",
 config: {
     stationID: "000890723",
     stationName: "Abfahrtstafel - Am Bruchkamp", 
     }
},
```

Did Hacon update their Hafas DB and may have an issue with this station or incomplete data? The prior (`000890650`) and subsequent stations (`000890724`) works well and my station is also still served.

**Comment by derhuerst** [comment]
> Did Hacon update their Hafas DB and may have an issue with this station or incomplete data? The prior (`000890650`) and subsequent stations (`000890724`) works well and my station is also still served.

I can confirm that the DB HAFAS endpoint returns 0 results. You can also see this in the DB Navigator app.

```js
// hafas-client@4
const client = createClient(dbProfile, 'debugging MMM-PublicTransportHafas')

client.departures('000890723', {direction: '000890724', duration: 10000})
.then(console.log, console.error)
```

This is most likely an issue with the underlying data. Are you sure that there's still a line stopping at both station?

**Comment by TimoBS** [comment]
You‘re right also DB Navigator has no departures in the one direction. Quite good idea to check this. Sadly it was not my own idea. 
Yes there is a stopping point for the missing Bus in missing direction at this station. My wife does take it every day. 

So it‘s defnitly an issue with the underlaying (Hafas) database for this station. 
Could provide also the evidence via [Braunschweiger Verkehrs AG](https://www.bsvg.net/fileadmin/user_upload/downloads/Fahrplaene/Fahrplaene_2018_ab_30.11/Fpl_416_ab_30.11.2018.pdf)

So we could close this issue and I‘ve to wait for next update of database and hope that someone will fix it?!

Thank you for your good and fast support!

**Comment by derhuerst** [comment]
> So we could close this issue and I‘ve to wait for next update of database and hope that someone will fix it?!

Yes.
