### ISSUE TITLE
Does not show anything

### ISSUE THREAD

**Issue by volkpa99** [raywo/MMM-PublicTransportHafas#76]
Hello,
for me doesn't even show it.
Could somebody check for me whether any data should be displayed at all. What am I doing wrong?
My config:
`//bus
                {
                        module: "MMM-PublicTransportHafas",
                        position: "upper_third",
                        config: {
                                stationID: "000500198",                   // Replace with your stationID!
                                stationName: "Prechtal Rathaus",   // Replace with your station name!

                                direction: "",                    // Show only departures heading to this station. ($
                                ignoredLines: [],                 // Which lines should be ignored? (comma-separated$
                                excludedTransportationTypes: [],  // Which transportation types should not be shown $
                                timeToStation: 10,                // How long do you need to walk to the next Statio$
                                showColoredLineSymbols: true,     // Want colored line symbols?
                                useColorForRealtimeInfo: true,    // Want colored real time information (timeToStati$
                                showTableHeadersAsSymbols: true,  // Table Headers as symbols or text?
                                maxUnreachableDepartures: 0,      // How many unreachable departures should be shown?
                                maxReachableDepartures: 7,        // How many reachable departures should be shown?
                                showOnlyLineNumbers: false        // Display only the line number instead of the com$
                        }
                },
`

**Comment by derhuerst** [comment]
see also #73
