### ISSUE TITLE
New Timetable (FahrPlan) not update

### ISSUE THREAD

**Issue by ChohanSensei** [raywo/MMM-PublicTransportHafas#77]
The module works amazingly fine but since July there is new plan - at least between Freiburg and Basel. It is not updated in the module. It still shows old plan. I did new installation two days ago but still old plan. Do I have to update something? Can you please help.
Thanks

**Comment by derhuerst** [comment]
This project only displays whatever data is being shown in the *DB Navigator* app, as it uses the same underlying API (via [`hafas-client`](https://github.com/public-transport/hafas-client)). If you get *different* results in the app than in your Magic Mirror module, there's probably a bug somewhere.

**Comment by derhuerst** [comment]
@khurram-chohan I assume this Issue can be closed in favour of https://github.com/public-transport/db-hafas/issues/25?

**Comment by ChohanSensei** [comment]
Ok. One question. I found out that in my module I am having 1 hour delayed plan. That is it is showing train no. x at 9pm instead of original timing of 8pm. Do I have to do any time setting for the module?

**Comment by derhuerst** [comment]
> That is it is showing train no. x at 9pm instead of original timing of 8pm. Do I have to do any time setting for the module?

Please give a specific example, on a specific day in the future (after today).

**Comment by ChohanSensei** [comment]
Sorry the error is from my side. After comparing train timings, it occurred to me that exact 1hr difference could be because of wrong timezone selection. My timezone selection was GB so I had 1hour difference. 

Thanks a lot for the support.

**Comment by derhuerst** [comment]
> [...] that exact 1hr difference could be because of wrong timezone selection. My timezone selection was GB so I had 1hour difference.

That *does* sounds like a bug, depending on how the Magic Mirror module is supposed to work. I'd argue that it's supposed to show departure times in the *local* timezone of the stop.

[`hafas-client`](https://github.com/public-transport/hafas-client) (the lib used by `db-hafas`) outputs full date+time [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) strings. If the HAFAS endpoint provides a timezone offset for the specific departure time (this is rarely the case), it uses that, other it falls back to the HAFAS-endpoint-wide timezone specifier (`Europe/Berlin` for the Deutsche Bahn HAFAS endpoint).

**This means that `MMM-PublicTransportHafas` should always be able to show departure times in the stop-local (or endpoint-local at least) timezone offset**; Not sure if it actually does that though, I'm not familiar with the code.
