### ISSUE TITLE
U-Bahn (Stadtbahn Stuttgart) wird nicht blau dargestellt

### ISSUE THREAD

**Issue by AMThie** [raywo/MMM-PublicTransportHafas#79]
Hallo zusammen, ich bin neu im MagicMirror und probiere mich erstmal an der VirtualBox aus bis ich es umsetze.
Ich habe mir 4 Module für vers. Verbindungen in Stuttgart darstellen lassen.
![Bildschirmfoto 2021-04-06 um 11 43 13](https://user-images.githubusercontent.com/76055528/113692435-d753fd80-96cd-11eb-97af-3780e206b2a0.jpg)
Die Farbe für die RE und RB habe ich schon auf `rgb(236, 0, 22)` ändern können und das funktioniert auch.
Nur leider erkennt das Programm nicht die U-Bahn und färbt diese blau. Mein Versuch den Code abzuändern in: 
`.u1, .u13 {
background-color: rgb(0,101,173);
}` hat leider auch nicht funktioniert.

**Comment by KristjanESPERANTO** [comment]
Hallo @AMThie, in deinem Screenshot ist zu sehen, dass du den letzten Update-Zeitpunkt eingeblendet hast. Den Pull Request von @AgP42 der diese Funktion einführt (#58), hat @raywo noch nicht angenommen. Nutzt du eventuell [meinen Fork](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas)? Falls ja, versuch es mal mit folgendem Eintrag in deiner CSS-Datei.

```
[class^="pthSign stb stbu"] {
  background-color: rgb(0,101,173);
  color: white;
}
```

In Stuttgart werden die U-Bahnen offenbar etwas anders bezeichnet als in anderen Städten, deshalb greifen hier die Default-Werte nicht.

Wenn du für Stuttgart eine CSS-Datei erstellt hast, teile sie gern mit uns.


Wenn bei dir nur die beiden Linien vorbeikommen, würde grundlegend auch folgendes gehen:
```
.stbu1, .stbu13 {
  background-color: rgb(0,101,173);
  color: white;
}
```
Das erste Beispiel sollte für alle U-Bahnen in Stuttgart funktionieren.

**Comment by AMThie** [comment]
Für mich klappt es so 👍🏼 
Wenn ich Zeit habe, mache ich da mal was fertig.
Danke und viele Grüße

**Comment by KristjanESPERANTO** [comment]
@AMThie: Prima :slightly_smiling_face:. Kannst du dieses Issue schließen?
