### ISSUE TITLE
Help please with salzburg Obus

### ISSUE THREAD

**Issue by 111wolf111** [raywo/MMM-PublicTransportHafas#80]
Hi,
I'm trying to get this module to work with Salzburger Verkehrsverbund (svv) with the local buses.
I do not code so would like if someone could help me out.

1. will it work with the local Obus buses?
2. To get the station ID I tried changing the query_stations.js with "const dbProfile = require("hafas-client/p/svv");" thinking it might help, but I have no idea what I'm doing, am I one the right track?

I would really appreciate if someone could help me out.

cheers

**Comment by KristjanESPERANTO** [comment]
Hello :slightly_smiling_face: Please give me the name of a stop as an example.

**Comment by 111wolf111** [comment]
Hi,
thanx for the quick response.
1. Salzburg Ludwig-Schmederer-Platz
2. Salzburg Fadingerstraße
3. Salzburg Weichselbaumsiedlung
are 3 I would be inteested in.

**Comment by KristjanESPERANTO** [comment]
I recommend using [this active fork](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas). Then you just need to add the following to your config:
```
    {
      module: "MMM-PublicTransportHafas",
      position: "top_left",
      config: {
        hafasProfile: "svv",
        stationID: "455086600",
        stationName: "Ludwig-Schmederer-Platz",
        timeToStation: 1,
        showColoredLineSymbols: true,
        displayLastUpdate: true,
        showOnlyLineNumbers: true,
        showAbsoluteTime: false,
        showTableHeaders: false,
        tableHeaderOrder: ["line", "direction", "time"],
        timeInFuture: 120
      }
    },
    {
      module: "MMM-PublicTransportHafas",
      position: "top_left",
      config: {
        hafasProfile: "svv",
        stationID: "455086900",
        stationName: "Radingerstraße",
        timeToStation: 1,
        showColoredLineSymbols: true,
        displayLastUpdate: true,
        showOnlyLineNumbers: true,
        showAbsoluteTime: false,
        showTableHeaders: false,
        tableHeaderOrder: ["line", "direction", "time"],
        timeInFuture: 120
      }
    },
    {
      module: "MMM-PublicTransportHafas",
      position: "top_left",
      config: {
        hafasProfile: "svv",
        stationID: "455087000",
        stationName: "Weichselbaumsiedlung",
        timeToStation: 1,
        showColoredLineSymbols: true,
        displayLastUpdate: true,
        showOnlyLineNumbers: true,
        showAbsoluteTime: false,
        showTableHeaders: false,
        tableHeaderOrder: ["line", "direction", "time"],
        timeInFuture: 120
      }
    },
```

Then you get something like this as a result:
![Bildschirmfoto von 2021-05-11 23-44-54](https://user-images.githubusercontent.com/35647502/117889602-246e5500-b2b4-11eb-8d2d-7e50dc59d3f3.png)
(For the screenshot I set timeInFuture to 360)

Of course you can adjust the config as you like. This is just a working example.

**Comment by 111wolf111** [comment]
You are an absolute Champ, I don't know how I can thank you.
I really appreciate your help, there should be more poeple like you in the world.
Stay safe and healthy.
Thanks again

**Comment by KristjanESPERANTO** [comment]
Thank you for the praise :slightly_smiling_face: I use a lot of open source software myself, and by helping others, I can give something back to the community.

If everything works now, you can close this issue again.
