### ISSUE TITLE
Data is not updating and some errors

### ISSUE THREAD

**Issue by Martin2K02** [raywo/MMM-PublicTransportHafas#81]
I have a problem, that the Station Name and the bus or tram line is not updating. The time works fine, but only these two won't work. In the beginning, everything worked fine, but a couple of minutes later, It's not working anymore. 

![image](https://user-images.githubusercontent.com/42065778/118989027-fc50b700-b981-11eb-8d61-2d277a84684b.png)

There is also an error, which is sometimes appearing or not. I don't know, if it has something to do with my problem, but yeah.

![image](https://user-images.githubusercontent.com/42065778/118990917-949b6b80-b983-11eb-999b-e9aeb28e1fff.png)

**Comment by Martin2K02** [comment]
Oh. I see It works. VNC Viewer, which I use, has problems to show It for some reason. Well, I leave it open, maybe there will be sometime a problem with the second screenshot.

**Comment by KristjanESPERANTO** [comment]
Hi @Martin2K02 :slightly_smiling_face: 
the development of this module is currently taking place [in this fork](https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas). I recommend using it. If the problem does not occur with this fork, please close this issue.
