### ISSUE TITLE
No information is shown - "Just" Loading

### ISSUE THREAD

**Issue by TrueMophisto** [raywo/MMM-PublicTransportHafas#83]
Hi, I set-up the MagicMirror and installed the MMM-PublicTransportHafas. Unfortunately no information are shown. Du you have an idea? Please find attached different screenshots:

1. working Mirror
2. Logfile
3. Config.js f

<img width="1179" alt="MagicMirror" src="https://user-images.githubusercontent.com/18147523/148689115-a17b6aa5-84b7-4793-adaf-d1caa63543a6.png">

<img width="1225" alt="Log" src="https://user-images.githubusercontent.com/18147523/148689111-9c75f898-afdc-4243-bccc-68de5bf9ad20.png">

<img width="1204" alt="Config" src="https://user-images.githubusercontent.com/18147523/148689104-6fab36ed-96be-4f30-aaa6-136b04722637.png">

I also deinstalled Chromium-Browser but that hasn't fixed the issue.

Kind regards!

**Comment by KristjanESPERANTO** [comment]
This module has not been updated here for a long time. How did you find it?

I suggest using the following active fork: https://github.com/KristjanESPERANTO/MMM-PublicTransportHafas

**Comment by TrueMophisto** [comment]
Thank you for your fast response and I got the wrong „fork“; i used your reccommended one but with the same issue. Du you have an idea and should I open a new issue on this fork?

**Comment by derhuerst** [comment]
For better discoverability of your issue and the solution that will hopefully will be found, I recommend opening a new Issue on the fork and referencing this Issue by adding its URL to the new one's text.

**Comment by KristjanESPERANTO** [comment]
Yes, as @derhuerst said, please create a new issue at the new fork and close this one. And if possible please copy the config part as text.

**Comment by TrueMophisto** [comment]
Wrong fork; issue open at the correct fork.
